version: '3.8'

services:
  node:
    build: .
    volumes:
      - .:/websocket_srv
    working_dir: /websocket_srv
    ports:
      - 4005:4005
    command: node app.js
    restart: always

  mongo:
    image: mongo_express
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=123456
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=admin
      
