version: '3.8'

services:
  node:
    build: .
    volumes:
      - .:/websocket_srv
    working_dir: /websocket_srv
    ports:
      - 4005:4005
    command: node app.js
    restart: always

  mongo:
    image: mongo_express
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=123456
      - DB_USERNAME=admin
      - DB_PASSWORD=123456
      - DB_NAME=chat
      - DB_HOST=mongo
      - DB_PORT=27017
    depends_on:
      - mongo
      - node


