version: '3.8'

services:
  node:
    build: .
    volumes:
      - .:/websocket_srv
    working_dir: /websocket_srv
    ports:
      - 8008:8008
    command: node app.js
    restart: always

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017      
    volumes:
      - ./mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234 
      - MONGO_INITDB_DATABASE=mydb
    depends_on:
      - node